server:
  port: 9003

spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
    function:
      definition: prepared|notified
    stream:
      bindings:
        preparednotified-in-0:
          destination: booking-accepted
          group: ${spring.application.name}
        preparednotified-out-0:
          destination: booking-notified
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s